name: actions-project
on: [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: list files and folders and pwd
       run: |
         pwd
         ls -a    

     - name: checkout-code
       uses: actions/checkout@v4
     - name: list after checkout-code 
       run: ls -a
       